apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
resources:
  - ../../base/canary-smoke
  - gcp-backend-policy-stable.yaml
  - gcp-backend-policy-canary.yaml
labels:
  - pairs:
      linklynx.ai/environment: prod
patches:
  - target:
      kind: Rollout
      name: canary-smoke
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
