export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
  keywords?: string[];
}

export const EMOJI_CATEGORIES = [
  { id: "recent", name: "最近使った絵文字", icon: "🕐" },
  { id: "people", name: "人物", icon: "😀" },
  { id: "nature", name: "自然", icon: "🐱" },
  { id: "food", name: "食べ物", icon: "🍔" },
  { id: "activity", name: "アクティビティ", icon: "⚽" },
  { id: "travel", name: "旅行", icon: "✈️" },
  { id: "objects", name: "オブジェクト", icon: "💡" },
  { id: "symbols", name: "シンボル", icon: "❤️" },
  { id: "flags", name: "フラグ", icon: "🏁" },
] as const;

export type EmojiCategoryId = (typeof EMOJI_CATEGORIES)[number]["id"];

export const EMOJI_DATA: EmojiItem[] = [
  // People
  { emoji: "😀", name: "にっこり", category: "people", keywords: ["smile", "happy"] },
  { emoji: "😃", name: "嬉しい顔", category: "people", keywords: ["happy", "joy"] },
  { emoji: "😄", name: "笑顔", category: "people", keywords: ["smile", "laugh"] },
  { emoji: "😁", name: "にやり", category: "people", keywords: ["grin"] },
  { emoji: "😆", name: "大笑い", category: "people", keywords: ["laugh"] },
  { emoji: "😅", name: "汗笑い", category: "people", keywords: ["sweat", "smile"] },
  { emoji: "🤣", name: "転げ回って笑う", category: "people", keywords: ["rofl", "laugh"] },
  { emoji: "😂", name: "嬉し泣き", category: "people", keywords: ["joy", "tears"] },
  { emoji: "🙂", name: "微笑み", category: "people", keywords: ["smile"] },
  { emoji: "🙃", name: "逆さま", category: "people", keywords: ["upside"] },
  { emoji: "😉", name: "ウインク", category: "people", keywords: ["wink"] },
  { emoji: "😊", name: "照れ笑い", category: "people", keywords: ["blush"] },
  { emoji: "😇", name: "天使", category: "people", keywords: ["angel", "halo"] },
  { emoji: "🥰", name: "愛の顔", category: "people", keywords: ["love", "hearts"] },
  { emoji: "😍", name: "ハートの目", category: "people", keywords: ["love", "heart eyes"] },
  { emoji: "🤩", name: "スターの目", category: "people", keywords: ["star", "excited"] },
  { emoji: "😘", name: "投げキス", category: "people", keywords: ["kiss"] },
  { emoji: "😗", name: "キス", category: "people", keywords: ["kiss"] },
  { emoji: "😋", name: "おいしい", category: "people", keywords: ["yum", "delicious"] },
  { emoji: "😛", name: "舌出し", category: "people", keywords: ["tongue"] },
  { emoji: "😜", name: "ウインク舌出し", category: "people", keywords: ["wink", "tongue"] },
  { emoji: "🤪", name: "おどけ顔", category: "people", keywords: ["crazy", "zany"] },
  { emoji: "😝", name: "ぎゅっと舌出し", category: "people", keywords: ["tongue", "squint"] },
  { emoji: "🤑", name: "お金の顔", category: "people", keywords: ["money", "rich"] },
  { emoji: "🤗", name: "ハグ", category: "people", keywords: ["hug"] },
  { emoji: "🤭", name: "てへぺろ", category: "people", keywords: ["oops"] },
  { emoji: "🤫", name: "しー", category: "people", keywords: ["quiet", "shush"] },
  { emoji: "🤔", name: "考え中", category: "people", keywords: ["think", "hmm"] },
  { emoji: "😐", name: "無表情", category: "people", keywords: ["neutral"] },
  { emoji: "😑", name: "ジト目", category: "people", keywords: ["expressionless"] },
  { emoji: "😶", name: "口なし", category: "people", keywords: ["mute", "silent"] },
  { emoji: "😏", name: "ニヤリ", category: "people", keywords: ["smirk"] },
  { emoji: "😒", name: "しらけ", category: "people", keywords: ["unamused"] },
  { emoji: "🙄", name: "やれやれ", category: "people", keywords: ["eye roll"] },
  { emoji: "😬", name: "歯むき出し", category: "people", keywords: ["grimace"] },
  { emoji: "😮‍💨", name: "ため息", category: "people", keywords: ["sigh", "exhale"] },
  { emoji: "😢", name: "泣き顔", category: "people", keywords: ["cry", "sad"] },
  { emoji: "😭", name: "大泣き", category: "people", keywords: ["sob", "cry"] },
  { emoji: "😤", name: "怒り鼻息", category: "people", keywords: ["angry", "huff"] },
  { emoji: "😡", name: "怒った顔", category: "people", keywords: ["angry", "mad"] },
  { emoji: "🤬", name: "罵倒", category: "people", keywords: ["swear", "angry"] },
  { emoji: "😈", name: "悪魔笑い", category: "people", keywords: ["devil", "evil"] },
  { emoji: "👋", name: "手を振る", category: "people", keywords: ["wave", "hello", "bye"] },
  { emoji: "👍", name: "いいね", category: "people", keywords: ["thumbs up", "good"] },
  { emoji: "👎", name: "よくない", category: "people", keywords: ["thumbs down", "bad"] },
  { emoji: "👏", name: "拍手", category: "people", keywords: ["clap"] },
  { emoji: "🙏", name: "お願い", category: "people", keywords: ["pray", "please"] },

  // Nature
  { emoji: "🐶", name: "犬", category: "nature", keywords: ["dog", "puppy"] },
  { emoji: "🐱", name: "猫", category: "nature", keywords: ["cat", "kitten"] },
  { emoji: "🐭", name: "ネズミ", category: "nature", keywords: ["mouse"] },
  { emoji: "🐹", name: "ハムスター", category: "nature", keywords: ["hamster"] },
  { emoji: "🐰", name: "ウサギ", category: "nature", keywords: ["rabbit", "bunny"] },
  { emoji: "🦊", name: "キツネ", category: "nature", keywords: ["fox"] },
  { emoji: "🐻", name: "クマ", category: "nature", keywords: ["bear"] },
  { emoji: "🐼", name: "パンダ", category: "nature", keywords: ["panda"] },
  { emoji: "🐨", name: "コアラ", category: "nature", keywords: ["koala"] },
  { emoji: "🐯", name: "トラ", category: "nature", keywords: ["tiger"] },
  { emoji: "🦁", name: "ライオン", category: "nature", keywords: ["lion"] },
  { emoji: "🐮", name: "牛", category: "nature", keywords: ["cow"] },
  { emoji: "🐷", name: "豚", category: "nature", keywords: ["pig"] },
  { emoji: "🐸", name: "カエル", category: "nature", keywords: ["frog"] },
  { emoji: "🐵", name: "サル", category: "nature", keywords: ["monkey"] },
  { emoji: "🙈", name: "見ざる", category: "nature", keywords: ["see no evil"] },
  { emoji: "🙉", name: "聞かざる", category: "nature", keywords: ["hear no evil"] },
  { emoji: "🙊", name: "言わざる", category: "nature", keywords: ["speak no evil"] },
  { emoji: "🐒", name: "おサル", category: "nature", keywords: ["monkey"] },
  { emoji: "🐔", name: "ニワトリ", category: "nature", keywords: ["chicken"] },
  { emoji: "🐧", name: "ペンギン", category: "nature", keywords: ["penguin"] },
  { emoji: "🐦", name: "鳥", category: "nature", keywords: ["bird"] },
  { emoji: "🌸", name: "桜", category: "nature", keywords: ["cherry blossom", "sakura"] },
  { emoji: "🌻", name: "ひまわり", category: "nature", keywords: ["sunflower"] },
  { emoji: "🌲", name: "木", category: "nature", keywords: ["tree", "evergreen"] },

  // Food
  { emoji: "🍏", name: "青リンゴ", category: "food", keywords: ["apple", "green"] },
  { emoji: "🍎", name: "リンゴ", category: "food", keywords: ["apple", "red"] },
  { emoji: "🍐", name: "洋ナシ", category: "food", keywords: ["pear"] },
  { emoji: "🍊", name: "ミカン", category: "food", keywords: ["orange", "tangerine"] },
  { emoji: "🍋", name: "レモン", category: "food", keywords: ["lemon"] },
  { emoji: "🍌", name: "バナナ", category: "food", keywords: ["banana"] },
  { emoji: "🍉", name: "スイカ", category: "food", keywords: ["watermelon"] },
  { emoji: "🍇", name: "ブドウ", category: "food", keywords: ["grapes"] },
  { emoji: "🍓", name: "イチゴ", category: "food", keywords: ["strawberry"] },
  { emoji: "🍈", name: "メロン", category: "food", keywords: ["melon"] },
  { emoji: "🍒", name: "チェリー", category: "food", keywords: ["cherry"] },
  { emoji: "🍑", name: "モモ", category: "food", keywords: ["peach"] },
  { emoji: "🍍", name: "パイナップル", category: "food", keywords: ["pineapple"] },
  { emoji: "🥝", name: "キウイ", category: "food", keywords: ["kiwi"] },
  { emoji: "🍅", name: "トマト", category: "food", keywords: ["tomato"] },
  { emoji: "🍆", name: "ナス", category: "food", keywords: ["eggplant"] },
  { emoji: "🥑", name: "アボカド", category: "food", keywords: ["avocado"] },
  { emoji: "🥦", name: "ブロッコリー", category: "food", keywords: ["broccoli"] },
  { emoji: "🥒", name: "キュウリ", category: "food", keywords: ["cucumber"] },
  { emoji: "🍔", name: "ハンバーガー", category: "food", keywords: ["burger", "hamburger"] },
  { emoji: "🍟", name: "ポテトフライ", category: "food", keywords: ["fries", "french fries"] },
  { emoji: "🍕", name: "ピザ", category: "food", keywords: ["pizza"] },
  { emoji: "🍣", name: "寿司", category: "food", keywords: ["sushi"] },
  { emoji: "🍜", name: "ラーメン", category: "food", keywords: ["ramen", "noodles"] },
  { emoji: "🍰", name: "ケーキ", category: "food", keywords: ["cake", "shortcake"] },

  // Activity
  { emoji: "⚽", name: "サッカー", category: "activity", keywords: ["soccer", "football"] },
  { emoji: "🏀", name: "バスケ", category: "activity", keywords: ["basketball"] },
  { emoji: "🏈", name: "アメフト", category: "activity", keywords: ["football"] },
  { emoji: "⚾", name: "野球", category: "activity", keywords: ["baseball"] },
  { emoji: "🥎", name: "ソフトボール", category: "activity", keywords: ["softball"] },
  { emoji: "🎾", name: "テニス", category: "activity", keywords: ["tennis"] },
  { emoji: "🏐", name: "バレーボール", category: "activity", keywords: ["volleyball"] },
  { emoji: "🏉", name: "ラグビー", category: "activity", keywords: ["rugby"] },
  { emoji: "🎱", name: "ビリヤード", category: "activity", keywords: ["billiards", "pool"] },
  { emoji: "🏓", name: "卓球", category: "activity", keywords: ["ping pong", "table tennis"] },
  { emoji: "🎮", name: "ゲーム", category: "activity", keywords: ["game", "controller"] },
  { emoji: "🎲", name: "サイコロ", category: "activity", keywords: ["dice"] },
  { emoji: "🎯", name: "的", category: "activity", keywords: ["target", "dart"] },
  { emoji: "🎵", name: "音符", category: "activity", keywords: ["music", "note"] },
  { emoji: "🎶", name: "音楽", category: "activity", keywords: ["music", "notes"] },
  { emoji: "🎤", name: "マイク", category: "activity", keywords: ["microphone", "karaoke"] },
  { emoji: "🎧", name: "ヘッドフォン", category: "activity", keywords: ["headphones"] },
  { emoji: "🎬", name: "映画", category: "activity", keywords: ["movie", "film"] },
  { emoji: "🎨", name: "パレット", category: "activity", keywords: ["art", "paint"] },
  { emoji: "🎪", name: "サーカス", category: "activity", keywords: ["circus", "tent"] },
  { emoji: "🏆", name: "トロフィー", category: "activity", keywords: ["trophy", "win"] },
  { emoji: "🥇", name: "金メダル", category: "activity", keywords: ["gold", "medal", "first"] },

  // Travel
  { emoji: "✈️", name: "飛行機", category: "travel", keywords: ["airplane", "flight"] },
  { emoji: "🚀", name: "ロケット", category: "travel", keywords: ["rocket", "launch"] },
  { emoji: "🚗", name: "車", category: "travel", keywords: ["car", "automobile"] },
  { emoji: "🚕", name: "タクシー", category: "travel", keywords: ["taxi", "cab"] },
  { emoji: "🚌", name: "バス", category: "travel", keywords: ["bus"] },
  { emoji: "🚎", name: "トロリーバス", category: "travel", keywords: ["trolleybus"] },
  { emoji: "🚂", name: "機関車", category: "travel", keywords: ["train", "locomotive"] },
  { emoji: "🚆", name: "電車", category: "travel", keywords: ["train"] },
  { emoji: "🚇", name: "地下鉄", category: "travel", keywords: ["metro", "subway"] },
  { emoji: "🚢", name: "船", category: "travel", keywords: ["ship", "boat"] },
  { emoji: "🏠", name: "家", category: "travel", keywords: ["house", "home"] },
  { emoji: "🏢", name: "ビル", category: "travel", keywords: ["building", "office"] },
  { emoji: "🏰", name: "城", category: "travel", keywords: ["castle"] },
  { emoji: "🗾", name: "日本地図", category: "travel", keywords: ["japan", "map"] },
  { emoji: "🗻", name: "富士山", category: "travel", keywords: ["fuji", "mountain"] },
  { emoji: "🌅", name: "日の出", category: "travel", keywords: ["sunrise"] },
  { emoji: "🌆", name: "夕暮れの街", category: "travel", keywords: ["cityscape", "dusk"] },
  { emoji: "🌇", name: "夕焼け", category: "travel", keywords: ["sunset"] },
  { emoji: "🌉", name: "橋の夜景", category: "travel", keywords: ["bridge", "night"] },
  { emoji: "🎡", name: "観覧車", category: "travel", keywords: ["ferris wheel"] },

  // Objects
  { emoji: "💡", name: "電球", category: "objects", keywords: ["idea", "light", "bulb"] },
  { emoji: "🔦", name: "懐中電灯", category: "objects", keywords: ["flashlight"] },
  { emoji: "💻", name: "パソコン", category: "objects", keywords: ["laptop", "computer"] },
  { emoji: "📱", name: "スマホ", category: "objects", keywords: ["phone", "mobile"] },
  { emoji: "📷", name: "カメラ", category: "objects", keywords: ["camera", "photo"] },
  { emoji: "📺", name: "テレビ", category: "objects", keywords: ["tv", "television"] },
  { emoji: "🔔", name: "ベル", category: "objects", keywords: ["bell", "notification"] },
  { emoji: "📚", name: "本", category: "objects", keywords: ["books"] },
  { emoji: "📝", name: "メモ", category: "objects", keywords: ["memo", "note"] },
  { emoji: "📎", name: "クリップ", category: "objects", keywords: ["paperclip"] },
  { emoji: "✂️", name: "ハサミ", category: "objects", keywords: ["scissors", "cut"] },
  { emoji: "🔑", name: "鍵", category: "objects", keywords: ["key"] },
  { emoji: "🔒", name: "ロック", category: "objects", keywords: ["lock", "locked"] },
  { emoji: "🔓", name: "解除", category: "objects", keywords: ["unlock", "unlocked"] },
  { emoji: "⏰", name: "目覚まし時計", category: "objects", keywords: ["alarm", "clock"] },
  { emoji: "💰", name: "お金袋", category: "objects", keywords: ["money", "bag"] },
  { emoji: "💎", name: "宝石", category: "objects", keywords: ["gem", "diamond"] },
  { emoji: "🎁", name: "プレゼント", category: "objects", keywords: ["gift", "present"] },
  { emoji: "🎀", name: "リボン", category: "objects", keywords: ["ribbon"] },
  { emoji: "🛒", name: "カート", category: "objects", keywords: ["cart", "shopping"] },

  // Symbols
  { emoji: "❤️", name: "赤いハート", category: "symbols", keywords: ["love", "heart", "red"] },
  { emoji: "🧡", name: "オレンジのハート", category: "symbols", keywords: ["heart", "orange"] },
  { emoji: "💛", name: "黄色いハート", category: "symbols", keywords: ["heart", "yellow"] },
  { emoji: "💚", name: "緑のハート", category: "symbols", keywords: ["heart", "green"] },
  { emoji: "💙", name: "青いハート", category: "symbols", keywords: ["heart", "blue"] },
  { emoji: "💜", name: "紫のハート", category: "symbols", keywords: ["heart", "purple"] },
  { emoji: "🖤", name: "黒いハート", category: "symbols", keywords: ["heart", "black"] },
  { emoji: "💔", name: "割れたハート", category: "symbols", keywords: ["broken heart"] },
  { emoji: "✨", name: "キラキラ", category: "symbols", keywords: ["sparkles", "shine"] },
  { emoji: "🔥", name: "炎", category: "symbols", keywords: ["fire", "hot"] },
  { emoji: "💯", name: "100点", category: "symbols", keywords: ["hundred", "perfect"] },
  { emoji: "✅", name: "チェックマーク", category: "symbols", keywords: ["check", "done"] },
  { emoji: "❌", name: "バツ", category: "symbols", keywords: ["x", "cross", "no"] },
  { emoji: "⭕", name: "丸", category: "symbols", keywords: ["circle", "o"] },
  { emoji: "❓", name: "はてな", category: "symbols", keywords: ["question"] },
  { emoji: "❗", name: "びっくり", category: "symbols", keywords: ["exclamation"] },
  { emoji: "💤", name: "zzz", category: "symbols", keywords: ["sleep", "zzz"] },
  { emoji: "💬", name: "吹き出し", category: "symbols", keywords: ["speech", "bubble"] },
  { emoji: "👀", name: "目", category: "symbols", keywords: ["eyes", "look"] },
  { emoji: "🎉", name: "お祝い", category: "symbols", keywords: ["party", "celebration"] },

  // Flags
  { emoji: "🏁", name: "チェッカーフラッグ", category: "flags", keywords: ["checkered", "flag", "race"] },
  { emoji: "🚩", name: "三角旗", category: "flags", keywords: ["flag", "red"] },
  { emoji: "🎌", name: "交差した旗", category: "flags", keywords: ["crossed flags"] },
  { emoji: "🏴", name: "黒旗", category: "flags", keywords: ["black flag"] },
  { emoji: "🏳️", name: "白旗", category: "flags", keywords: ["white flag", "surrender"] },
  { emoji: "🇯🇵", name: "日本", category: "flags", keywords: ["japan", "flag"] },
  { emoji: "🇺🇸", name: "アメリカ", category: "flags", keywords: ["us", "usa", "flag"] },
  { emoji: "🇬🇧", name: "イギリス", category: "flags", keywords: ["uk", "britain", "flag"] },
  { emoji: "🇫🇷", name: "フランス", category: "flags", keywords: ["france", "flag"] },
  { emoji: "🇩🇪", name: "ドイツ", category: "flags", keywords: ["germany", "flag"] },
  { emoji: "🇰🇷", name: "韓国", category: "flags", keywords: ["korea", "flag"] },
  { emoji: "🇨🇳", name: "中国", category: "flags", keywords: ["china", "flag"] },
  { emoji: "🇧🇷", name: "ブラジル", category: "flags", keywords: ["brazil", "flag"] },
  { emoji: "🇮🇹", name: "イタリア", category: "flags", keywords: ["italy", "flag"] },
  { emoji: "🇪🇸", name: "スペイン", category: "flags", keywords: ["spain", "flag"] },
];
