import type { NotificationData } from "./notification-types";

export const MOCK_NOTIFICATIONS: NotificationData[] = [
  {
    id: "notif-1",
    type: "mention",
    serverId: "s-1",
    serverName: "開発サーバー",
    serverIcon: undefined,
    channelId: "ch-1",
    channelName: "一般",
    author: { displayName: "田中太郎", avatar: null },
    content: "@あなた 新しいPRのレビューをお願いできますか？",
    timestamp: "2024-01-20T16:30:00.000Z",
    read: false,
  },
  {
    id: "notif-2",
    type: "reply",
    serverId: "s-1",
    serverName: "開発サーバー",
    serverIcon: undefined,
    channelId: "ch-2",
    channelName: "質問",
    author: { displayName: "佐藤花子", avatar: null },
    content: "その問題は最新バージョンで修正されていますよ。",
    timestamp: "2024-01-20T16:00:00.000Z",
    read: false,
  },
  {
    id: "notif-3",
    type: "message",
    serverId: "s-2",
    serverName: "ゲーミング",
    serverIcon: undefined,
    channelId: "ch-3",
    channelName: "雑談",
    author: { displayName: "鈴木一郎", avatar: null },
    content: "今夜一緒にプレイしませんか？",
    timestamp: "2024-01-20T15:30:00.000Z",
    read: false,
  },
  {
    id: "notif-4",
    type: "mention",
    serverId: "s-1",
    serverName: "開発サーバー",
    serverIcon: undefined,
    channelId: "ch-4",
    channelName: "お知らせ",
    author: { displayName: "管理者", avatar: null },
    content: "@everyone 明日のミーティングは14時に変更になりました。",
    timestamp: "2024-01-20T14:00:00.000Z",
    read: false,
  },
  {
    id: "notif-5",
    type: "friend_request",
    author: { displayName: "山田次郎", avatar: null },
    content: "フレンドリクエストが届いています。",
    timestamp: "2024-01-20T13:00:00.000Z",
    read: false,
  },
  {
    id: "notif-6",
    type: "reply",
    serverId: "s-3",
    serverName: "デザインコミュニティ",
    serverIcon: undefined,
    channelId: "ch-5",
    channelName: "フィードバック",
    author: { displayName: "高橋美咲", avatar: null },
    content: "素晴らしいデザインですね！色使いがとても良いと思います。",
    timestamp: "2024-01-20T12:00:00.000Z",
    read: true,
  },
  {
    id: "notif-7",
    type: "message",
    serverId: "s-1",
    serverName: "開発サーバー",
    serverIcon: undefined,
    channelId: "ch-1",
    channelName: "一般",
    author: { displayName: "中村健太", avatar: null },
    content: "デプロイが完了しました。動作確認をお願いします。",
    timestamp: "2024-01-20T11:00:00.000Z",
    read: true,
  },
  {
    id: "notif-8",
    type: "mention",
    serverId: "s-2",
    serverName: "ゲーミング",
    serverIcon: undefined,
    channelId: "ch-6",
    channelName: "攻略",
    author: { displayName: "小林遥", avatar: null },
    content: "@あなた このボスの攻略法知ってる？",
    timestamp: "2024-01-20T10:00:00.000Z",
    read: true,
  },
  {
    id: "notif-9",
    type: "message",
    author: { displayName: "佐藤花子", avatar: null },
    content: "週末の予定を教えてください！",
    timestamp: "2024-01-20T09:00:00.000Z",
    read: false,
  },
  {
    id: "notif-10",
    type: "reply",
    serverId: "s-1",
    serverName: "開発サーバー",
    serverIcon: undefined,
    channelId: "ch-2",
    channelName: "質問",
    author: { displayName: "田中太郎", avatar: null },
    content: "ドキュメントに記載されているのでそちらを参照してください。",
    timestamp: "2024-01-20T08:00:00.000Z",
    read: true,
  },
  {
    id: "notif-11",
    type: "mention",
    serverId: "s-3",
    serverName: "デザインコミュニティ",
    serverIcon: undefined,
    channelId: "ch-7",
    channelName: "コンペ",
    author: { displayName: "高橋美咲", avatar: null },
    content: "@あなた 今月のデザインコンペに参加しませんか？",
    timestamp: "2024-01-19T22:00:00.000Z",
    read: true,
  },
  {
    id: "notif-12",
    type: "message",
    serverId: "s-2",
    serverName: "ゲーミング",
    serverIcon: undefined,
    channelId: "ch-3",
    channelName: "雑談",
    author: { displayName: "鈴木一郎", avatar: null },
    content: "新しいアップデートが来ましたね！",
    timestamp: "2024-01-19T20:00:00.000Z",
    read: true,
  },
];
