import type { Sound } from "./soundboard-types";

export const mockSounds: Sound[] = [
  { id: "s1", name: "クリケット", emoji: "🦗", duration: 2.1, favorite: true, category: "animal" },
  {
    id: "s2",
    name: "ドラムロール",
    emoji: "🥁",
    duration: 3.5,
    favorite: false,
    category: "music",
  },
  { id: "s3", name: "エアホーン", emoji: "📯", duration: 1.8, favorite: true, category: "effect" },
  { id: "s4", name: "拍手", emoji: "👏", duration: 2.0, favorite: false, category: "effect" },
  { id: "s5", name: "ため息", emoji: "😮‍💨", duration: 1.2, favorite: true, category: "voice" },
  { id: "s6", name: "笑い声", emoji: "😂", duration: 2.8, favorite: false, category: "voice" },
  { id: "s7", name: "サスペンス", emoji: "😱", duration: 4.0, favorite: false, category: "music" },
  { id: "s8", name: "バネ", emoji: "🌀", duration: 0.8, favorite: true, category: "effect" },
  { id: "s9", name: "猫の鳴き声", emoji: "🐱", duration: 1.5, favorite: false, category: "animal" },
  {
    id: "s10",
    name: "犬の鳴き声",
    emoji: "🐶",
    duration: 1.3,
    favorite: false,
    category: "animal",
  },
  {
    id: "s11",
    name: "ファンファーレ",
    emoji: "🎺",
    duration: 3.2,
    favorite: true,
    category: "music",
  },
  { id: "s12", name: "ブー", emoji: "👎", duration: 1.0, favorite: false, category: "voice" },
  { id: "s13", name: "ベル", emoji: "🔔", duration: 1.1, favorite: false, category: "effect" },
  { id: "s14", name: "爆発", emoji: "💥", duration: 2.5, favorite: false, category: "effect" },
  { id: "s15", name: "チャイム", emoji: "🎵", duration: 1.6, favorite: true, category: "music" },
  {
    id: "s16",
    name: "鳥のさえずり",
    emoji: "🐦",
    duration: 3.0,
    favorite: false,
    category: "animal",
  },
];
